import { describe, test } from "@jest/globals";
import { a_pmv } from "../../src/models/a_pmv.js";
import { testDataUrls } from "./comftest";
import { loadTestData, validateResult } from "./testUtils"; // Use the utils
import { createRequire } from "module";

let returnArray = false;

// use top-level await to load test data before tests are defined.
let { testData, tolerances } = await loadTestData(
  testDataUrls.aPmv,
  returnArray,
);

describe("a_pmv", () => {
  // automatically number each test case
  test.each(testData.data)("Test case #%#", (testCase) => {
    const { inputs, outputs: expectedOutput } = testCase;
    const { tdb, tr, vr, rh, met, clo, a_coefficient, wme } = inputs;

    const modelResult = a_pmv(tdb, tr, vr, rh, met, clo, a_coefficient, wme);

    validateResult(modelResult, expectedOutput, tolerances, inputs);
  });
});

// ---------------------------------------------------------------------------
// Scalar tests against snapshot
// Expected values generated by: python scripts/python/generate_snapshots.py
// To update: edit SNAPSHOT_CASES in generate_snapshots.py, re-run, commit JSON
//
// Scenarios covered:
//   SC-1  Neutral comfort conditions
//   SC-2  Warm conditions with positive a_pmv
//   SC-3  Cool conditions with negative a_pmv
//   SC-4  Out-of-range tdb with limit_inputs=true → a_pmv is NaN
//   SC-5  Higher a_coefficient with warm inputs
// ---------------------------------------------------------------------------
const require = createRequire(import.meta.url);
const snapshotData = require("../../tests/snapshots/a_pmv.json");

describe("a_pmv scalar tests (snapshot)", () => {
  test.each(snapshotData.cases)("$name", ({ inputs, expected }) => {
    const { tdb, tr, vr, rh, met, clo, a_coefficient, wme, limit_inputs } =
      inputs;

    const jsResult = a_pmv(tdb, tr, vr, rh, met, clo, a_coefficient, wme ?? 0, {
      limit_inputs: limit_inputs ?? true,
    });

    // tolerances loaded dynamically from validation data URL at top of this file
    validateResult(jsResult, expected, tolerances, inputs);
  });
});
