import { describe, test } from "@jest/globals";
import { adaptive_en } from "../../src/models/adaptive_en";
import { testDataUrls } from "./comftest";
import { loadTestData, validateResult } from "./testUtils"; // use the utils
import { createRequire } from "module";

let returnArray = false;

let { testData, tolerance } = await loadTestData(
  testDataUrls.adaptiveEn,
  returnArray,
);

describe("adaptive_en", () => {
  test.each(testData.data)("Test case #%#", (testCase) => {
    const { inputs, outputs: expectedOutput } = testCase;
    const { tdb, tr, t_running_mean, v, units } = inputs;
    const modelResult = adaptive_en(tdb, tr, t_running_mean, v, units);

    validateResult(modelResult, expectedOutput, tolerance, inputs);
  });
});

// ---------------------------------------------------------------------------
// Scalar tests against snapshot
// Expected values generated by: python scripts/python/generate_snapshots.py
// To update: edit SNAPSHOT_CASES in generate_snapshots.py, re-run, commit JSON
//
// Scenarios covered:
//   SC-1  Neutral comfort, t_running_mean within range → category II acceptable
//   SC-2  Warm indoor with high t_running_mean → category III only
//   SC-3  Cool indoor → not acceptable in any category
//   SC-4  Out-of-range t_running_mean → tmp_cmf is NaN
//   SC-5  Higher air speed → wider comfort range
// ---------------------------------------------------------------------------
const require = createRequire(import.meta.url);
const snapshotData = require("../../tests/snapshots/adaptive_en.json");

describe("adaptive_en scalar tests (snapshot)", () => {
  test.each(snapshotData.cases)("$name", ({ inputs, expected }) => {
    const { tdb, tr, t_running_mean, v, units, limit_inputs } = inputs;

    const jsResult = adaptive_en(
      tdb,
      tr,
      t_running_mean,
      v,
      units ?? "SI",
      limit_inputs ?? true,
    );

    validateResult(jsResult, expected, tolerance, inputs);
  });
});
