import { describe } from "@jest/globals";
import { ankle_draft } from "../../src/models/ankle_draft.js";
import { testDataUrls } from "./comftest";
import { loadTestData, validateResult } from "./testUtils"; // Import shared utilities
import { createRequire } from "module";

let returnArray = false;

// use top-level await to load test data before tests are defined.
let { testData, tolerances } = await loadTestData(
  testDataUrls.ankleDraft,
  returnArray,
);

describe("ankle_draft", () => {
  test.each(testData.data)("Test case #%#", (testCase) => {
    const { inputs, outputs: expectedOutput } = testCase;
    const { tdb, tr, vr, rh, met, clo, v_ankle, units } = inputs;
    const modelResult = ankle_draft(tdb, tr, vr, rh, met, clo, v_ankle, units);

    validateResult(modelResult, expectedOutput, tolerances, inputs);
  });
});

// ---------------------------------------------------------------------------
// Scalar tests against snapshot
// Expected values generated by: python scripts/python/generate_snapshots.py
// To update: edit SNAPSHOT_CASES in generate_snapshots.py, re-run, commit JSON
//
// Scenarios covered:
//   SC-1  Typical office conditions → low ankle draft PPD
//   SC-2  Higher ankle velocity → increased PPD
//   SC-3  Warm conditions with moderate ankle draft
//   SC-4  High ankle velocity → PPD exceeds 20% not acceptable
//   SC-5  IP units conversion
// ---------------------------------------------------------------------------
const require = createRequire(import.meta.url);
const snapshotData = require("../../tests/snapshots/ankle_draft.json");

describe("ankle_draft scalar tests (snapshot)", () => {
  test.each(snapshotData.cases)("$name", ({ inputs, expected }) => {
    const { tdb, tr, vr, rh, met, clo, v_ankle, units } = inputs;

    const jsResult = ankle_draft(
      tdb,
      tr,
      vr,
      rh,
      met,
      clo,
      v_ankle,
      units ?? "SI",
    );

    validateResult(jsResult, expected, tolerances, inputs);
  });
});
