import { describe } from "@jest/globals";
import { at } from "../../src/models/at.js";
import { testDataUrls } from "./comftest";
import { loadTestData, validateResult } from "./testUtils"; // Import shared utilities
import { createRequire } from "module";

let returnArray = false;

// use top-level await to load test data before tests are defined.
let { testData, tolerances } = await loadTestData(testDataUrls.at, returnArray);

describe("at", () => {
  test.each(testData.data)("Test case #%#", (testCase) => {
    const { inputs, outputs: expectedOutput } = testCase;
    const { tdb, rh, v, q } = inputs;
    const modelResult = at(tdb, rh, v, q);

    validateResult(modelResult, expectedOutput, tolerances, inputs);
  });
});

// ---------------------------------------------------------------------------
// Scalar tests against snapshot
// Expected values generated by: python scripts/python/generate_snapshots.py
// To update: edit SNAPSHOT_CASES in generate_snapshots.py, re-run, commit JSON
//
// Scenarios covered:
//   SC-1  Warm and humid conditions without solar radiation
//   SC-2  Cool and windy conditions without solar radiation → wind chill effect reduces AT below tdb
//   SC-3  Hot conditions with high relative humidity → humidity raises AT above tdb
//   SC-4  Solar radiation included (q=200 W/m2) → AT higher than without solar load
//   SC-5  Low humidity conditions without solar radiation
// ---------------------------------------------------------------------------
const require = createRequire(import.meta.url);
const snapshotData = require("../../tests/snapshots/at.json");

describe("at scalar tests (snapshot)", () => {
  test.each(snapshotData.cases)("$name", ({ inputs, expected }) => {
    const { tdb, rh, v, q } = inputs;

    const jsResult = at(tdb, rh, v, q);

    validateResult(jsResult, expected, tolerances, inputs);
  });
});
