const prefixURL =
  "https://raw.githubusercontent.com/FedericoTartarini/validation-data-comfort-models/refs/heads/main/";

export const testDataUrls = {
  adaptiveEn: prefixURL + "ts_adaptive_en.json",
  adaptiveAshrae: prefixURL + "ts_adaptive_ashrae.json",
  aPmv: prefixURL + "ts_a_pmv.json",
  ankleDraft: prefixURL + "ts_ankle_draft.json",
  at: prefixURL + "ts_at.json",
  athb: prefixURL + "ts_athb.json",
  cloTout: prefixURL + "ts_clo_tout.json",
  coolingEffect: prefixURL + "ts_cooling_effect.json",
  discomfortIndex: prefixURL + "ts_discomfort_index.json",
  ePmv: prefixURL + "ts_e_pmv.json",
  heatIndex: prefixURL + "ts_heat_index.json",
  humidex: prefixURL + "ts_humidex.json",
  net: prefixURL + "ts_net.json",
  petSteady: prefixURL + "ts_pet_steady.json",
  phs: prefixURL + "ts_phs.json",
  pmv: prefixURL + "ts_pmv.json",
  pmvPpd: prefixURL + "ts_pmv_ppd.json",
  use_fans_heatwaves: prefixURL + "ts_use_fans_heatwaves.json",
  utci: prefixURL + "ts_utci.json",
  verticalTmpGradPpd: prefixURL + "ts_vertical_tmp_grad_ppd.json",
  wc: prefixURL + "ts_wind_chill.json",
  wbgt: prefixURL + "ts_wbgt.json",
  twoNodes: prefixURL + "ts_two_nodes.json",
  solarGain: prefixURL + "ts_solar_gain.json",
  setTmp: prefixURL + "ts_set.json",
};
