// Reference values verified against pythermalcomfort v3.9.1.
// Values generated by: python3 generate_reference_values.py
import { describe, expect, test } from "@jest/globals";
import { pmv_ppd_iso } from "../../src/models/pmv_ppd_iso.js";

describe("pmv_ppd_iso", () => {
  test("standard office — neutral comfort baseline", () => {
    const r = pmv_ppd_iso(25, 25, 0.1, 50, 1.2, 0.5);
    // PMV scale [-3, 3]; 1 decimal place ≈ ±0.05 tolerance
    expect(r.pmv).toBeCloseTo(0.08, 1);
    // PPD is a percentage [5, 100]; 0 decimal places ≈ ±0.5% tolerance
    expect(r.ppd).toBeCloseTo(5.1, 0);
  });

  test("warm and humid — positive PMV response", () => {
    const r = pmv_ppd_iso(30, 30, 0.3, 70, 1.5, 0.7);
    // PMV scale [-3, 3]; 1 decimal place ≈ ±0.05 tolerance
    expect(r.pmv).toBeCloseTo(1.91, 1);
    // PPD is a percentage [5, 100]; 0 decimal places ≈ ±0.5% tolerance
    expect(r.ppd).toBeCloseTo(72.6, 0);
  });

  test("cool and dry — negative PMV response", () => {
    const r = pmv_ppd_iso(20, 20, 0.1, 40, 1.0, 1.0);
    // PMV scale [-3, 3]; 1 decimal place ≈ ±0.05 tolerance
    expect(r.pmv).toBeCloseTo(-0.94, 1);
    // PPD is a percentage [5, 100]; 0 decimal places ≈ ±0.5% tolerance
    expect(r.ppd).toBeCloseTo(23.7, 0);
  });

  test("hot conditions — out-of-range inputs return NaN", () => {
    // tdb=35 exceeds the ISO 7730 upper limit of 30 °C. With
    // limit_inputs=true (the default), the function returns NaN.
    const r = pmv_ppd_iso(35, 35, 0.5, 80, 2.0, 0.3);
    expect(r.pmv).toBeNaN();
    expect(r.ppd).toBeNaN();
  });

  test("returns an object with pmv and ppd properties", () => {
    const r = pmv_ppd_iso(25, 25, 0.1, 50, 1.2, 0.5);
    expect(r).toHaveProperty("pmv");
    expect(r).toHaveProperty("ppd");
    expect(typeof r.pmv).toBe("number");
    expect(typeof r.ppd).toBe("number");
  });
});
