import { expect, describe, it } from "@jest/globals";
import { deep_close_to_obj } from "../test_utilities";
import { two_nodes } from "../../src/models/two_nodes.js";

describe("two_nodes", () => {
  it("should be a function", () => {
    expect(two_nodes).toBeInstanceOf(Function);
  });

  it.each([
    {
      tdb: 25,
      tr: 25,
      v: 0.3,
      rh: 50,
      met: 1.2,
      clo: 0.5,
      wme: undefined,
      body_surface_area: undefined,
      p_atmospheric: undefined,
      body_position: undefined,
      max_skin_blood_flow: undefined,
      kwargs: undefined,
      expected: {
        e_skin: 16.2,
        e_rsw: 7,
        e_max: 159.9,
        q_sensible: 47.6,
        q_skin: 63.8,
        q_res: 5.2,
        t_core: 36.9,
        t_skin: 33.7,
        m_bl: 12.9,
        m_rsw: 10.3,
        w: 0.1,
        w_max: 0.6,
        set: 23.6,
        et: 25,
        pmv_gagge: 0.1,
        pmv_set: -0,
        disc: 0.1,
        t_sens: 0.1,
      },
    },
    {
      tdb: 30,
      tr: 35,
      v: 0.5,
      rh: 60,
      met: 1.5,
      clo: 0.3,
      wme: 0,
      body_surface_area: 1.8258,
      p_atmospheric: 101325,
      body_position: "standing",
      max_skin_blood_flow: 90,
      kwargs: undefined,
      expected: {
        e_skin: 60.4,
        e_rsw: 51.9,
        e_max: 193.8,
        q_sensible: 21.1,
        q_skin: 81.5,
        q_res: 5,
        t_core: 37,
        t_skin: 35.1,
        m_bl: 31.6,
        m_rsw: 76.3,
        w: 0.3,
        w_max: 0.6,
        set: 29.3,
        et: 32.5,
        pmv_gagge: 1.6,
        pmv_set: 1.1,
        disc: 1.9,
        t_sens: 1.4,
      },
    },
    {
      tdb: 30,
      tr: 35,
      v: 0.5,
      rh: 60,
      met: 1.5,
      clo: 0.3,
      wme: 0,
      body_surface_area: 1.8258,
      p_atmospheric: 101325,
      body_position: "sitting",
      max_skin_blood_flow: 90,
      kwargs: undefined,
      expected: {
        e_skin: 60.3,
        e_rsw: 51.8,
        e_max: 193.7,
        q_sensible: 21.2,
        q_skin: 81.5,
        q_res: 5,
        t_core: 37,
        t_skin: 35.1,
        m_bl: 31.6,
        m_rsw: 76.2,
        w: 0.3,
        w_max: 0.6,
        set: 29.1,
        et: 32.4,
        pmv_gagge: 1.6,
        pmv_set: 1.1,
        disc: 1.9,
        t_sens: 1.4,
      },
    },
    {
      tdb: 30,
      tr: 35,
      v: 0.5,
      rh: 60,
      met: 1.5,
      clo: 0.3,
      wme: 0,
      body_surface_area: 1.8258,
      p_atmospheric: 101325,
      body_position: undefined,
      max_skin_blood_flow: 80,
      kwargs: undefined,
      expected: {
        e_skin: 60.4,
        e_rsw: 51.9,
        e_max: 193.8,
        q_sensible: 21.1,
        q_skin: 81.5,
        q_res: 5,
        t_core: 37,
        t_skin: 35.1,
        m_bl: 31.6,
        m_rsw: 76.3,
        w: 0.3,
        w_max: 0.6,
        set: 29.3,
        et: 32.5,
        pmv_gagge: 1.6,
        pmv_set: 1.1,
        disc: 1.9,
        t_sens: 1.4,
      },
    },
  ])(
    "returns $expected when tdb is $tdb, tr is $tr, v is $v, rh is $rh, met is $met, clo is $clo ",
    ({
      tdb,
      tr,
      v,
      rh,
      met,
      clo,
      wme,
      body_surface_area,
      p_atmospheric,
      body_position,
      max_skin_blood_flow,
      kwargs,
      expected,
    }) => {
      const result = two_nodes(
        tdb,
        tr,
        v,
        rh,
        met,
        clo,
        wme,
        body_surface_area,
        p_atmospheric,
        body_position,
        max_skin_blood_flow,
        kwargs,
      );
      deep_close_to_obj(result, expected, 1);
    },
  );
});
