import { expect, describe, it } from "@jest/globals";
import { deep_close_to_obj } from "../test_utilities";
import { use_fans_heatwaves } from "../../src/models/use_fans_heatwave";

describe("use_fans_heatwaves", () => {
  it("should be a function", () => {
    expect(use_fans_heatwaves).toBeInstanceOf(Function);
  });

  it.each([
    {
      tdb: 25,
      tr: 25,
      v: 0.3,
      rh: 50,
      met: 1.2,
      clo: 0.5,
      wme: undefined,
      body_surface_area: undefined,
      p_atmospheric: undefined,
      body_position: undefined,
      max_skin_blood_flow: undefined,
      kwargs: undefined,
      expected: {
        e_skin: 18.1,
        e_rsw: 10.0,
        e_max: 145.0,
        q_sensible: 45.7,
        q_skin: 63.8,
        q_res: 5.2,
        t_core: 36.9,
        t_skin: 33.8,
        m_bl: 13.6,
        m_rsw: 14.6,
        w: 0.1,
        w_max: 0.7,
        heat_strain_blood_flow: 0.0,
        heat_strain_w: 0.0,
        heat_strain_sweating: 0.0,
        heat_strain: 0.0,
      },
    },
    {
      tdb: 30,
      tr: 35,
      v: 0.5,
      rh: 60,
      met: 1.5,
      clo: 0.3,
      wme: 0,
      body_surface_area: 1.8258,
      p_atmospheric: 101325,
      body_position: "standing",
      max_skin_blood_flow: 80,
      kwargs: undefined,
      expected: {
        e_skin: 60.4,
        e_rsw: 51.9,
        e_max: 193.8,
        q_sensible: 21.1,
        q_skin: 81.5,
        q_res: 5,
        t_core: 37,
        t_skin: 35.1,
        m_bl: 31.6,
        m_rsw: 76.3,
        w: 0.3,
        w_max: 0.6,
        set: 29.3,
        et: 32.5,
        pmv_gagge: 1.6,
        pmv_set: 1.1,
        disc: 1.9,
        t_sens: 1.4,
      },
    },
    {
      tdb: 30,
      tr: 35,
      v: 0.5,
      rh: 60,
      met: 1.5,
      clo: 0.3,
      wme: 0,
      body_surface_area: 1.8258,
      p_atmospheric: 101325,
      body_position: "sitting",
      max_skin_blood_flow: 80,
      kwargs: undefined,
      expected: {
        e_skin: 60.3,
        e_rsw: 51.8,
        e_max: 193.7,
        q_sensible: 21.2,
        q_skin: 81.5,
        q_res: 5,
        t_core: 37,
        t_skin: 35.1,
        m_bl: 31.6,
        m_rsw: 76.2,
        w: 0.3,
        w_max: 0.6,
        set: 29.1,
        et: 32.4,
        pmv_gagge: 1.6,
        pmv_set: 1.1,
        disc: 1.9,
        t_sens: 1.4,
      },
    },
    {
      tdb: 40,
      tr: 35,
      v: 0.2,
      rh: 60,
      met: 1.5,
      clo: 0.3,
      wme: 0,
      body_surface_area: undefined,
      p_atmospheric: undefined,
      body_position: "standing",
      max_skin_blood_flow: 80,
      kwargs: undefined,
      expected: {
        e_skin: 71.6,
        e_rsw: 69.9,
        e_max: 98,
        q_sensible: -4.6,
        q_skin: 67,
        q_res: 2.2,
        t_core: 37.5,
        t_skin: 36.9,
        m_bl: 80,
        m_rsw: 102.9,
        w: 0.7,
        w_max: 0.7,
        set: 38.9,
        et: 40.3,
        pmv_gagge: 3.1,
        pmv_set: 3.5,
        disc: 5.2,
        t_sens: 3.3,
      },
    },
    {
      tdb: 25,
      tr: 25,
      v: 0.3,
      rh: 50,
      met: 1.2,
      clo: 0.5,
      wme: 0,
      body_surface_area: 1.8258,
      p_atmospheric: 101325,
      body_position: "standing",
      max_skin_blood_flow: 80,
      kwargs: { calculate_ce: true },
      expected: { set: 22.886158290953105 },
    },
  ])(
    "returns $expected when tdb is $tdb, tr is $tr, v is $v, rh is $rh, met is $met, clo is $clo ",
    ({
      tdb,
      tr,
      v,
      rh,
      met,
      clo,
      wme,
      body_surface_area,
      p_atmospheric,
      body_position,
      units,
      max_skin_blood_flow,
      kwargs,
      expected,
    }) => {
      const result = use_fans_heatwaves(
        tdb,
        tr,
        v,
        rh,
        met,
        clo,
        wme,
        body_surface_area,
        p_atmospheric,
        body_position,
        units,
        max_skin_blood_flow,
        kwargs,
      );
      deep_close_to_obj(result, expected, 1);
    },
  );
});
