declare namespace _default {
    export { heat_index };
    export { phs };
    export { humidex };
    export { net };
    export { wbgt };
    export { discomfort_index };
    export { discomfort_index_array };
    export { two_nodes };
    export { two_nodes_array };
    export { wc };
    export { adaptive_en };
    export { adaptive_en_array };
    export { at };
    export { set_tmp };
    export { set_tmp_array };
    export { adaptive_ashrae };
    export { adaptive_ashrae_array };
    export { solar_gain };
    export { cooling_effect };
    export { pmv_ppd };
    export { pmv_ppd_array };
    export { pmv };
    export { pmv_array };
    export { athb };
    export { athb_array };
    export { a_pmv };
    export { a_pmv_array };
}
export default _default;
import { heat_index } from "./heat_index.js";
import { phs } from "./phs.js";
import { humidex } from "./humidex.js";
import { net } from "./net.js";
import { wbgt } from "./wbgt.js";
import { discomfort_index } from "./discomfort_index.js";
import { discomfort_index_array } from "./discomfort_index.js";
import { two_nodes } from "./two_nodes.js";
import { two_nodes_array } from "./two_nodes.js";
import { wc } from "./wc.js";
import { adaptive_en } from "./adaptive_en.js";
import { adaptive_en_array } from "./adaptive_en.js";
import { at } from "./at.js";
import { set_tmp } from "./set_tmp.js";
import { set_tmp_array } from "./set_tmp.js";
import { adaptive_ashrae } from "./adaptive_ashrae.js";
import { adaptive_ashrae_array } from "./adaptive_ashrae.js";
import { solar_gain } from "./solar_gain.js";
import { cooling_effect } from "./cooling_effect.js";
import { pmv_ppd } from "./pmv_ppd.js";
import { pmv_ppd_array } from "./pmv_ppd.js";
import { pmv } from "./pmv.js";
import { pmv_array } from "./pmv.js";
import { athb } from "./athb.js";
import { athb_array } from "./athb.js";
import { a_pmv } from "./a_pmv.js";
import { a_pmv_array } from "./a_pmv.js";
//# sourceMappingURL=index.d.ts.map