name: Publish Package to NPM

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v5
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org/"

      - run: npm ci
      - run: npm run check:format
      - run: npm test
      - run: npm run build

      - name: Ensure git tag matches package version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          PACKAGE_VERSION="v$(npm pkg get version | tr -d '\"')"
          if [ "${GITHUB_REF_NAME}" != "${PACKAGE_VERSION}" ]; then
            echo "Tag ${GITHUB_REF_NAME} does not match package version ${PACKAGE_VERSION}"
            exit 1
          fi

  publish:
    runs-on: ubuntu-latest
    needs: checks
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v5
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org/"

      - run: npm ci
      - run: npm publish --provenance

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
